name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 🔥 CACHE DATASET HERE
      - name: Cache dataset
        uses: actions/cache@v4
        with:
          path: data/raw
          key: kaggle-dataset-v1

      # Only download if cache miss
      - name: Download dataset (only if needed)
        run: python scripts/0.download_datasets.py

      - name: Run scripts
        run: |
          for file in scripts/*.py; do
            python "$file"
          done